---
- name: 'Instala pacote de dependencia do sistema operacional'
  apt:
    name: [
      'php7.2', 
      'apache2', 
      'libapache2-mod-php7.2', 
      'php7.2-gd',   
      'php7.2-mysql']
    state: latest
  become: yes